DROP TABLE TBL_USER;


CREATE TABLE TBL_USER(
ID INT IDENTITY(1,1) NOT NULL,
FIRST_NAME VARCHAR(255) NOT NULL,
SECOND_NAME VARCHAR(255) NOT NULL,
SCORE INT NOT NULL,
GAME_TYPE VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

